name: Continous Deployment

on:
  push:
    branches:
      - master

env:
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Heroku and Login
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:login
      - name: Build Docker Image
        run: docker build --build-arg SSH_PRIVATE_KEY=${{secrets.SSH_PRIVATE_KEY}} --build-arg FRONT_REPOSITORY_URL=${{secrets.FRONT_REPOSITORY_URL}} -t ${{secrets.HEROKU_APP_NAME}}:${{github.run_id}} .
      - name: Deploy Docker Image
        run: |
          docker tag ${{secrets.HEROKU_APP_NAME}}:${{github.run_id}} registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
          docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
      - name: Release Backend
        run: heroku container:release web -a ${{secrets.HEROKU_APP_NAME}}

